### PR TITLE
add sanity checks to register

### PR DESCRIPTION
**Pull request by crossroads1112**
It occurred to me when writing the `Challenges` section, that weird things could happen if you called `after_check` when no check is being run or `{before,after}_every` when one is. This PR adds sanity checks to prevent that.

### CODE REVIEW

**Comment by Jelleas** [comment]
I like it! Small change though, instead of setting `internal.check_running` in `runner.py`, lets use our internal mechanism (`internal.register`) to set it.

**Comment by crossroads1112** [comment]
@Jelleas It was intentional that this was outside the register mechanism. For example, there is currently a bit of an inconsistency insofar as if in an `after_every` callback, you could register another `after_every` callback (which is bad) since the `_not_running_callback` gets run first.

**Comment by crossroads1112** [comment]
@Jelleas

**Comment by crossroads1112** [comment]
merged this into devdev

**Pull request closed without merging**
