### PR TITLE
Show html path within wsl

### LINKED ISSUE #275: Can't open result html when working from WSL
We've started to use check50 within WSL on Windows. Unfortunately when running check with `-l`/`--local` the url is in local Linux format and not accessible from a browser running in Windows.

### PR DESCRIPTION
**Pull request by TheRijn**
Closes #275 
Checking if we're running wsl using https://www.scivision.dev/python-detect-wsl/
Then converting the path within Ubuntu to a windows path with `wslpath -w`.

Tested with `check50 cs50/problems/2021/fall/hello --local` on macOS 12.2.1 with python 3.9.10 and WSL Ubuntu 20.04 with python 3.8.10

WSL result:
```To see the results in your browser go to file:///wsl.localhost/Ubuntu/tmp/tmpveuwk16x.html```

macOS result:
```To see the results in your browser go to file:///var/folders/j9/6b_9k8xs3pzcf8pxp6g08twh0000gn/T/tmp3iev6si6.html```

### CODE REVIEW

**Review by AalOsman — APPROVED** [review]

**Comment by Jelleas** [comment]
Tested again under a fresh install. Works fine in both WSL's Ubuntu terminal and the newish Windows terminal. Links should soon be clickable in Windows Terminal: https://github.com/microsoft/terminal/issues/7699

@rongxin-liu mind taking another look at this PR? We have a lot of WSL users and it'd be nice to have this merged 😀

**Review by AalOsman — APPROVED** [review]

**Review by AalOsman — COMMENTED** [review]
.

**Review by rongxin-liu — APPROVED** [review]

**Comment by rongxin-liu** [comment]
Looks good, merging! Thank you @TheRijn @Jelleas @AalOsman

**Review by AalOsman — COMMENTED** [review]
:)

**Pull request merged**
