### PR TITLE
fixes abspath issue

### PR DESCRIPTION
**Pull request by dmalan**

### CODE REVIEW

**Comment by kzidane** [comment]
Just to be sure was that supposed to fix https://github.com/cs50/check50/issues/79? Because it seems I'm still experiencing the same issue:

```
$ pip show check50
Name: check50
Version: 2.1.2
Summary: This is check50, with which you can check solutions to         problems for CS50.
Home-page: https://github.com/cs50/check50
Author: CS50
Author-email: sysadmins@cs50.harvard.edu
License: UNKNOWN
Location: /home/kzidane/github/cs50/check50
Requires: argparse, pexpect, requests, backports.shutil-which, termcolor, submit50
$ check50 --local cs50/2017/fall/hello
:) hello.c exists.
:( hello.c compiles.
    expected exit code 0, not 1
:| prints "hello, world\n"
    can't check until a frown turns upside down
$ check50 --local cs50/2017/fall/hello
Sorry, something's wrong! Let sysadmins@cs50.harvard.edu know!
$ ls
~  hello.c
```

**Comment by dmalan** [comment]
@brianyu28 ?

**Comment by brianyu28** [comment]
Per my comment on https://github.com/cs50/check50/pull/80, I don't think this actually fixes the issue, I'm getting the same results as Kareem when I test.

This should resolve, though:

https://github.com/cs50/check50/pull/82

**Comment by kzidane** [comment]
Closing in favor of #82. Let me know when ready to go!

**Pull request closed without merging**
