### PR TITLE
Add Flask testing API

### PR DESCRIPTION
**Pull request by crossroads1112**
See https://github.com/cs50/checks/pull/4 for checks written in the API.

We should also consider adding a way to denote that a check requires a certain version of `check50` (to prevent confusing errors if people try to run an old version of `check50` on their finance project.

### CODE REVIEW

**Comment by crossroads1112** [comment]
@dmalan Is this good to go?

**Comment by dmalan** [comment]
@brianyu28 want to try this with the other checks too, just for good measure?

**Comment by brianyu28** [comment]
I've tried this with the finance checks, seems to work!

**Comment by dmalan** [comment]
thanks!

**Pull request merged**
