### PR TITLE
Temporary fix for flask exception handling.

### PR DESCRIPTION
**Pull request by crossroads1112**
cs50/checks#34

### CODE REVIEW

**Comment by crossroads1112** [comment]
The correct solution to this problem requires changing the starter code (per the linked issue) but its too late to do this for fall. This fixes the issue in the meantime.

**Comment by dmalan** [comment]
@brianyu28 if we merge this, do we need to update cs50/ecs, or, @kzidane, will that happen automatically? Mind merging when ready?

**Comment by brianyu28** [comment]
We'll need to first merge `develop` into `master` to trigger an update on PyPi, then we'll need to re-pull the Docker image from ECS.

**Comment by brianyu28** [comment]
@kzidane, sound right to you? And if we do this now, do we run the risk of disrupting anyone's checks/submissions if ECS tasks are triggered during the pull?

**Comment by crossroads1112** [comment]
Just realized, we should catch `BaseException` so that e.g. `SystemExit` thrown in the app doesn't exit check50

**Comment by kzidane** [comment]
@dmalan won't happen automatically but I'll write a script to do that so when we deploy a new version of *50, it would trigger a build of our base image using Travis API.

@brianyu28 correct. Though based on previous experiences :innocent: I think we should wait 'til after the deadline?

**Comment by dmalan** [comment]
Yes, after noon please!

**Pull request merged**
