### PR TITLE
v3.0.9

### PR DESCRIPTION
**Pull request by crossroads1112**
If the docstring was unspecified in a check, "None" was displayed as the description to the student, but this seems kinda weird since the docstring is easy to forget. I figured a sensible default would be to use the name of the function replacing "_" with " ".

### CODE REVIEW

**Comment by Jelleas** [comment]
Accidentally piggy-backing on this pr, currently `--local` raises the following error:

```
Traceback (most recent call last):
  File "/usr/local/bin/check50", line 11, in <module>
    load_entry_point('check50==3.0.8', 'console_scripts', 'check50')()
  File "/usr/local/lib/python3.7/site-packages/check50/__main__.py", line 390, in main
    termcolor.cprint(_("To see the results in your browser go to {}").format(url), "white", attrs=["bold"])
UnboundLocalError: local variable 'url' referenced before assignment
```

https://github.com/cs50/check50/pull/180/commits/1000fe025c95a7c45891b537a8abd75444d3eaa4 fixes this

**Comment by Jelleas** [comment]
I do like the idea that this idea of using the name as a description is consistent with compiled .yml checks!

**Comment by Jelleas** [comment]
@crossroads1112 / @kzidane mind going over https://github.com/cs50/check50/pull/180/commits/1000fe025c95a7c45891b537a8abd75444d3eaa4 before pressing that big green merge button.

**Comment by crossroads1112** [comment]
Just fixed a minor thing wherein if they were in the IDE but not local, we wouldn't output a submit.cs50.io link. Fixed now.

**Comment by crossroads1112** [comment]
@jelleas We could tie this tie this PR to cs50/lib50#35 and remove this check https://github.com/cs50/check50/blob/9c9330e20b7b19ffd2eb6b0657a0b4fd30e7c08a/setup.py#L1-L2 but someone would need to merge that PR first.

**Pull request merged**
